### ISSUE TITLE
The .zip

### ISSUE THREAD

**Issue by misterj05** [Moonsett/LonelyLoner#1]
Not sure if it was intended or not but the zip in releases contains your whole directory structure rather than just the mod folder.

![2024-10-29_14-53](https://github.com/user-attachments/assets/d1cfc816-092d-4327-8c12-61de1dfd7849)

**Comment by Moonsett** [comment]
Aaa... Okay gotta fix that thank you

**Comment by Moonsett** [comment]
Okay... gotta get a GUI to manage zip files because I can't trust myself with the command line lol. Thank you for pointing this out to me I feel so embarrased

**Comment by misterj05** [comment]
Nah don't be embarrassed it happens to the best of us, I think I did this like 5 or 6 times before I realized lmao.
