### ISSUE TITLE
Not an issue but heavy suggestion...

### ISSUE THREAD

**Issue by meowisme** [Moonsett/LonelyLoner#2]
I know you already plan on adding light sources, which will be FANTASTIC. But... one of the light sources should be fireflies, if possible. I think it would make the night environment sooo lovely.

Please and thank you. :]

**Comment by Moonsett** [comment]
What a great idea, thanks for the suggestion! I've added fireflies around the map, mainly around the water reeds and some of the bushes. They emit a faint light around the map, which admittedly I would have loved to use as a stand in for something like lamp posts, but they don't really fit in everywhere, especially near the ocean. They should be visible from the beginning of sundown to the end of the night. The coding is... a bit shoddy, so I may have to come back to it, and hopefully it doesn't cause too much of a problem (if it does, please let me know!) I'd love to add a firefly jar prop as well, but I'm torn on whether or not I should add Lure as a dependency for that kinda thing, but if it's requested enough, then I would. Anyway, enjoy the additions, hopefully my code doesn't cause some sort of performance downgrade </3
